language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
#  - 7.0

#branches:
#  only:
#    - master

sudo: false

install:
  - travis_retry git clone https://github.com/jbboehr/hashcash.git --recursive
  - cd hashcash
  - autoreconf -fiv
  - ./configure --prefix=$HOME/hashcash
  - make
  - make install
  - make test
  - cd ..

script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_EXECUTABLE=`which php`
  - phpize
  - CPPFLAGS="-I$HOME/hashcash/include" CFLAGS="-L$HOME/hashcash/lib" ./configure --enable-hashcash --prefix=$HOME/hashcash
  - make
  - php run-tests.php -d extension=hashcash.so -d extension_dir=modules -n #-m

after_script:
  - for i in `ls tests/*.log 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done
#  - for i in `ls tests/*.mem 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done

